# Generated by Django 5.2.1 on 2025-05-22 08:34

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", django_countries.fields.CountryField(max_length=2)),
                ("supplier_name", models.CharField(max_length=100)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Process",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Laser Marker", "Laser Marker"),
                            ("Computer", "Computer"),
                            ("SDR", "SDR"),
                            ("Printer", "Printer"),
                            ("USB-Hub", "USB-Hub"),
                            ("JIG", "JIG"),
                            ("Other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("backup", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True, editable=False)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipments",
                        to="tb2_vsm.location",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Step",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                ("description", models.TextField(blank=True, default=None, null=True)),
                (
                    "cycle_time",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=None,
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "amount_of_operators",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "output_per_hour",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=None,
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "process",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="steps",
                        to="tb2_vsm.process",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="TonieboxProduction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Toniebox 1", "Toniebox 1"),
                            ("Toniebox 2", "Toniebox 2"),
                            ("Tonies", "Tonies"),
                            ("Book Tonies", "Book Tonies"),
                            ("Clever Tonies", "Clever Tonies"),
                            ("Disk", "Disk"),
                            ("Controller", "Controller"),
                            ("Soft Tonies", "Soft Tonies"),
                            ("Night Light", "Night Light"),
                            ("Other", "Other"),
                        ],
                        default="Toniebox 2",
                        max_length=20,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="toniebox_productions",
                        to="tb2_vsm.location",
                    ),
                ),
                (
                    "processes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="toniebox_productions",
                        to="tb2_vsm.process",
                    ),
                ),
            ],
            options={
                "verbose_name": "PSM Production",
                "verbose_name_plural": "PSM Productions",
            },
        ),
        migrations.AddField(
            model_name="location",
            name="toniebox_production",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="locations",
                to="tb2_vsm.tonieboxproduction",
            ),
        ),
        migrations.CreateModel(
            name="FactoryCloud",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fc_id", models.IntegerField(unique=True)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("url", models.URLField()),
                ("is_backup", models.BooleanField(default=False)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="factory_clouds",
                        to="tb2_vsm.location",
                    ),
                ),
                (
                    "production_lines",
                    models.ManyToManyField(
                        blank=True,
                        related_name="factory_clouds",
                        to="tb2_vsm.tonieboxproduction",
                    ),
                ),
            ],
        ),
    ]
