# Generated by Django 5.2.1 on 2025-05-08 11:08

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tb2_vsm", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="country",
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
