# Generated by Django 5.2.1 on 2025-05-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tb2_vsm", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="category",
            field=models.CharField(
                choices=[
                    ("Laser Marker", "Laser Marker"),
                    ("Computer", "Computer"),
                    ("SDR", "SDR"),
                    ("Printer", "Printer"),
                    ("USB-Hub", "USB-Hub"),
                    ("JIG", "JIG"),
                    ("TMS", "TMS"),
                    ("Display", "Display"),
                    ("NFC Reader", "NFC Reader"),
                    ("Camera", "Camera"),
                    ("Switch", "Switch"),
                    ("UPS", "UPS"),
                    ("Facility Controller", "Facility Controller"),
                    ("Scanner", "Scanner"),
                    ("Button", "Button"),
                    ("Light Strip", "Light Strip"),
                    ("Router", "Router"),
                    ("Other", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
