# Generated by Django 5.2.1 on 2025-05-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tb2_vsm", "0002_alter_equipment_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="production_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Toniebox 1", "Toniebox 1"),
                    ("Toniebox 2", "Toniebox 2"),
                    ("Tonies", "Tonies"),
                    ("Book Tonies", "Book Tonies"),
                    ("Clever Tonies", "Clever Tonies"),
                    ("Disk", "Disk"),
                    ("Controller", "Controller"),
                    ("Night Light", "Night Light"),
                    ("Soft Tonies", "Soft Tonies"),
                    ("Other", "Other"),
                ],
                default="Other",
                max_length=20,
                null=True,
            ),
        ),
    ]
