# Generated by Django 5.2.1 on 2025-05-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tb2_vsm", "0003_equipment_production_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
