# Generated by Django 5.2.1 on 2025-05-08 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tb2_vsm", "0003_step_description_step_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="process",
            name="step",
        ),
        migrations.AddField(
            model_name="process",
            name="toniebox_production",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="processes",
                to="tb2_vsm.tonieboxproduction",
            ),
        ),
        migrations.AddField(
            model_name="step",
            name="process",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="steps",
                to="tb2_vsm.process",
            ),
        ),
        migrations.AlterField(
            model_name="process",
            name="name",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="step",
            name="amount_of_operators",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="step",
            name="cycle_time",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="step",
            name="description",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="step",
            name="name",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="step",
            name="output_per_hour",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=6, null=True
            ),
        ),
    ]
