# Generated by Django 5.2.1 on 2025-05-08 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tb2_vsm", "0004_remove_process_step_process_toniebox_production_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tonieboxproduction",
            name="location",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="toniebox_productions",
                to="tb2_vsm.location",
            ),
        ),
    ]
