# Generated by Django 5.2.1 on 2025-06-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tb2_vsm", "0004_equipment_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="step",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
