# Generated by Django 5.2.1 on 2025-05-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tb2_vsm', '0005_tonieboxproduction_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tonieboxproduction',
            name='process',
        ),
        migrations.RemoveField(
            model_name='process',
            name='toniebox_production',
        ),
        migrations.AddField(
            model_name='process',
            name='toniebox_production',
            field=models.ManyToManyField(blank=True, related_name='processes', to='tb2_vsm.tonieboxproduction'),
        ),
    ]
