# Generated by Django 5.2.1 on 2025-06-26 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tb2_vsm", "0006_remove_equipment_serial_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="equipment",
            name="serial_numbers_array",
        ),
    ]
