# Generated by Django 5.2.1 on 2025-06-26 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tb2_vsm", "0007_remove_equipment_serial_numbers_array"),
    ]

    operations = [
        migrations.CreateModel(
            name="EquipmentSerialProxy",
            fields=[],
            options={
                "verbose_name": "Equipment Serial Number",
                "verbose_name_plural": "Equipment Serial Numbers",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("tb2_vsm.equipmentserial",),
        ),
    ]
