# Generated by Django 5.2.1 on 2025-06-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tb2_vsm", "0008_equipmentserialproxy"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipmentserial",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
