# Generated by Django 5.2.1 on 2025-05-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tb2_vsm', '0008_step_order_tonieboxproduction_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='amount_of_operators',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
