# Generated by Django 5.2.1 on 2025-07-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tb2_vsm", "0009_equipmentserial_notes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="process",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="process",
            name="order",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
