# Generated by Django 5.2.1 on 2025-05-21 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tb2_vsm', '0009_alter_step_amount_of_operators'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactoryCloud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fc_id', models.IntegerField(unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField()),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='factory_cloud', to='tb2_vsm.location')),
                ('production_lines', models.ManyToManyField(related_name='factory_clouds', to='tb2_vsm.tonieboxproduction')),
            ],
        ),
    ]
