# Generated by Django 5.2.4 on 2025-10-17 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tb2_vsm", "0011_alter_equipment_production_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="step",
            name="order",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=6, null=True
            ),
        ),
    ]
