# Generated by Django 5.2.4 on 2026-01-19 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tb2_vsm", "0012_alter_step_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="production_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Toniebox 1", "Toniebox 1"),
                    ("Toniebox 2", "Toniebox 2"),
                    ("Toniebox 2 G2", "Toniebox 2 G2"),
                    ("Tonies", "Tonies"),
                    ("Book Tonies", "Book Tonies"),
                    ("Clever Tonies", "Clever Tonies"),
                    ("Disc", "Disc"),
                    ("Controller", "Controller"),
                    ("Night Light", "Night Light"),
                    ("Soft Tonies", "Soft Tonies"),
                    ("Tag Cards", "Tag Cards"),
                    ("Other", "Other"),
                ],
                default="Other",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tonieboxproduction",
            name="category",
            field=models.CharField(
                choices=[
                    ("Toniebox 1", "Toniebox 1"),
                    ("Toniebox 2", "Toniebox 2"),
                    ("Toniebox 2 G2", "Toniebox 2 G2"),
                    ("Tonies", "Tonies"),
                    ("Book Tonies", "Book Tonies"),
                    ("Clever Tonies", "Clever Tonies"),
                    ("Disc", "Disc"),
                    ("Controller", "Controller"),
                    ("Soft Tonies", "Soft Tonies"),
                    ("Night Light", "Night Light"),
                    ("Tag Cards", "Tag Cards"),
                    ("Other", "Other"),
                ],
                default="Toniebox 2",
                max_length=20,
            ),
        ),
    ]
