# Generated by Django 5.2.1 on 2025-05-21 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tb2_vsm', '0012_factorycloud_is_backup_location_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ['order']},
        ),
    ]
