# Generated by Django 5.2.1 on 2025-05-21 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tb2_vsm', '0011_update_existing_equipment'),
        ('tb2_vsm', '0013_alter_step_options'),
    ]

    operations = [
    ]
