# Generated by Django 5.2.1 on 2025-05-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tb2_vsm", "0015_alter_tonieboxproduction_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tonieboxproduction",
            name="category",
            field=models.CharField(
                choices=[
                    ("Toniebox 1", "Toniebox 1"),
                    ("Toniebox 2", "Toniebox 2"),
                    ("Tonies", "Tonies"),
                ],
                default="Toniebox 2",
                max_length=20,
            ),
        ),
    ]
