# Generated by Django 5.2.1 on 2025-05-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tb2_vsm", "0017_alter_tonieboxproduction_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tonieboxproduction",
            name="category",
            field=models.CharField(
                choices=[
                    ("Toniebox 1", "Toniebox 1"),
                    ("Toniebox 2", "Toniebox 2"),
                    ("Tonies", "Tonies"),
                    ("Book Tonies", "Book Tonies"),
                    ("Clever Tonies", "Clever Tonies"),
                    ("Disk", "Disk"),
                    ("Controller", "Controller"),
                    ("Soft Tonies", "Soft Tonies"),
                    ("Night Light", "Night Light"),
                    ("Other", "Other"),
                ],
                default="Toniebox 2",
                max_length=20,
            ),
        ),
    ]
