version: '3.9'

services:
  db:
    image: postgres:15
    container_name: postgres_vsm
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: django_vsm
    command: sh -c "/entrypoint.sh"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
      - "8001:8001"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres_data:
