# Generated by Django 5.2.1 on 2025-06-20 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tb2_vsm", "0005_step_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessImprovementSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("suggestion_output", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="improvement_suggestions",
                        to="tb2_vsm.location",
                    ),
                ),
            ],
        ),
    ]
