# Generated by Django 5.2.1 on 2025-05-22 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tb2_vsm", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackupEquipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("minimum_quantity", models.PositiveIntegerField()),
                ("current_quantity", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Critical", "Critical"),
                            ("Low", "Low"),
                            ("Stable", "Stable"),
                        ],
                        editable=False,
                        max_length=10,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tb2_vsm.location",
                    ),
                ),
            ],
        ),
    ]
