# Generated by Django 5.2.1 on 2025-05-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spare_parts_management", "0003_backupequipment_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="backupequipment",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Price in Euros (€)",
                max_digits=20,
                null=True,
            ),
        ),
    ]
