# Generated by Django 5.2.1 on 2025-06-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spare_parts_management", "0005_alter_backupequipment_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="producer",
            name="ticket_system",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="producer",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="producer",
            name="telephone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
