# Generated by Django 5.2.1 on 2025-06-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "spare_parts_management",
            "0006_producer_ticket_system_alter_producer_email_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="backupequipment",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Optional notes of the backup equipment",
                null=True,
            ),
        ),
    ]
