# Generated by Django 5.2.4 on 2026-01-19 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spare_parts_management", "0007_backupequipment_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backupequipment",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Toniebox 1", "Toniebox 1"),
                    ("Toniebox 2", "Toniebox 2"),
                    ("Toniebox 2 G2", "Toniebox 2 G2"),
                    (" MTS", "MTS"),
                    ("TMS", "TMS"),
                    ("TMES", "TMES"),
                    ("Other", "Other"),
                ],
                default="Toniebox 2",
                max_length=20,
                null=True,
            ),
        ),
    ]
