# Generated by Django 5.2.1 on 2025-05-26 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tb2_vsm", "0004_equipment_quantity"),
    ]

    operations = [
        migrations.CreateModel(
            name="Maintenance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_maintenance_day", models.DateField(blank=True, null=True)),
                ("next_maintenance_day", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("expired", "Expired"), ("on_track", "On Track")],
                        max_length=10,
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tb2_vsm.equipment",
                    ),
                ),
            ],
        ),
    ]
