# Generated by Django 5.2.1 on 2025-05-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maintenance",
            name="status",
            field=models.CharField(
                choices=[("expired", "Expired"), ("on_track", "On Track")],
                editable=False,
                max_length=10,
            ),
        ),
    ]
