# Generated by Django 5.2.1 on 2025-05-26 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0002_alter_maintenance_status"),
        ("tb2_vsm", "0004_equipment_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maintenance",
            name="equipment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="tb2_vsm.equipment"
            ),
        ),
    ]
